apiVersion: v1
kind: Service
metadata:
  name: nodejs-guestbook-backend
  labels:
    app: nodejs-guestbook
    tier: backend
spec:
  selector:
    app: nodejs-guestbook
    tier: backend
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    nodePort: {{ .Values.backend.service.nodePort }}
