kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nodejs-guestbook-backend-route
  labels:
    app: nodejs-guestbook
    tier: backend
spec:
  to:
    kind: Service
    name: nodejs-guestbook-backend
    weight: 100
  port:
    targetPort: {{ .Values.backend.service.port }}
  wildcardPolicy: None
