apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-guestbook
    tier: backend
  name: nodejs-guestbook-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-guestbook
      tier: backend
  template:
    metadata:
      labels:
        app: nodejs-guestbook
        tier: backend
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: mvc-db-app-operator
      initContainers:
      - name: init-db-ready
        image: mongo:4
        command: ['/bin/sh', '-c']
        args:
          - echo "Waiting for mongodb to start...";until (mongo --host nodejs-guestbook-mongodb:27017 >/dev/null 2>&1) do echo "Waiting for connection for 2 sec."; sleep 2; done
      containers:
      - name: backend        
        image: "{{.Values.backend.image.registry}}/{{.Values.backend.image.repository}}:{{.Values.backend.image.tag}}"
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_DB_ADDR
          value: "nodejs-guestbook-mongodb:27017"
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: mongodb-credentials
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-credentials
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
