# permissions for end users to view mvcdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mvcdb-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - mvcdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - mvcdbs/status
  verbs:
  - get
