# permissions for end users to edit mvcdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mvcdb-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - mvcdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - mvcdbs/status
  verbs:
  - get
